# Generated by Django 4.0.1 on 2022-01-24 15:02

from django.db import migrations
import osmflex.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('osmflex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenityline',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenityline',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypoint',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='amenitypolygon',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpoint',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpolygon',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='capacity',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='door',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='entrance',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='highway',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='layer',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='level',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indoorline',
            name='room',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='capacity',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='door',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='entrance',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='highway',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='layer',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='level',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indoorpoint',
            name='room',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='capacity',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='door',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='entrance',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='highway',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='layer',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='level',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indoorpolygon',
            name='room',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='ele',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='height',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='material',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='ele',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='height',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='material',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='ele',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='height',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='material',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructurepolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landusepoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='landusepoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='landusepoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landusepolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='landusepolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='landusepolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leisurepoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='leisurepoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='leisurepoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leisurepolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='leisurepolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='leisurepolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naturalline',
            name='ele',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='naturalline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='naturalline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='naturalline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naturalpoint',
            name='ele',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='naturalpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='naturalpoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='naturalpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naturalpolygon',
            name='ele',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='naturalpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='naturalpolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='naturalpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placeline',
            name='admin_level',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeline',
            name='boundary',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='placeline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='placeline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='placeline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placepoint',
            name='admin_level',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placepoint',
            name='boundary',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='placepoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='placepoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='placepoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='placepolygon',
            name='admin_level',
            field=osmflex.helpers.OsmTagIntField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placepolygon',
            name='boundary',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='placepolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='placepolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='placepolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poiline',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipoint',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='poipolygon',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='bench',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='bus',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='lit',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='network',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='public_transport',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='shelter',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='surface',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportline',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='bench',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='bus',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='lit',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='network',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='public_transport',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='shelter',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='surface',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpoint',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='bench',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='bus',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='lit',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='network',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='public_transport',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='shelter',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='surface',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publictransportpolygon',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='access',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='major',
            field=osmflex.helpers.MajorRoadField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='maxspeed',
            field=osmflex.helpers.OsmSpeedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='oneway',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='route_cycle',
            field=osmflex.helpers.RouteCycleField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='route_foot',
            field=osmflex.helpers.RouteFootField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='route_motor',
            field=osmflex.helpers.RouteMotorField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadline',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='access',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='maxspeed',
            field=osmflex.helpers.OsmSpeedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadmajor',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='access',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='maxspeed',
            field=osmflex.helpers.OsmSpeedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpoint',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='access',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='layer',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='major',
            field=osmflex.helpers.MajorRoadField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='maxspeed',
            field=osmflex.helpers.OsmSpeedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='ref',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='route_cycle',
            field=osmflex.helpers.RouteCycleField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='route_foot',
            field=osmflex.helpers.RouteFootField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='route_motor',
            field=osmflex.helpers.RouteMotorField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadpolygon',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='brand',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='phone',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='website',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppoint',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='brand',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='city',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='housenumber',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='operator',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='phone',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='postcode',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='state',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='street',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='website',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='wheelchair',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='shoppolygon',
            name='wheelchair_desc',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='trafficline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='trafficline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='trafficpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='trafficpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='boat',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='geom',
            field=osmflex.helpers.OsmLineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='layer',
            field=osmflex.helpers.OsmTagIntField(),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waterline',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='boat',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='geom',
            field=osmflex.helpers.OsmPointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='layer',
            field=osmflex.helpers.OsmTagIntField(),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waterpoint',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='boat',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='bridge',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='geom',
            field=osmflex.helpers.OsmMultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='layer',
            field=osmflex.helpers.OsmTagIntField(),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='name',
            field=osmflex.helpers.OsmNameField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='osm_id',
            field=osmflex.helpers.OsmIdField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waterpolygon',
            name='tunnel',
            field=osmflex.helpers.OsmTagCharField(blank=True, max_length=1024, null=True),
        ),
    ]
